### ISSUE TITLE
Kibana Dashboard from Example cannot be loaded into Kibana 4

### ISSUE THREAD

**Issue by mikesand** [alerta/kibana-alerta#2]
The dashboard you provided for Kibana is explicitly for Kibana 3 and there is no migration tool provided by Kibana to move it and you can't load it into Kibana 4. Looks like it needs to be recreated from scratch. I'm going to take a swing at some of it if I have time this week but I've never used Kibana so I'm not sure I'll have much to contribute but let's see.

**Comment by satterly** [comment]
Ok. Thanks. Have a go and let me know how you get on.

**Comment by mikesand** [comment]
I have an updated one to submit. It's two json files.
[Alerta-Kibana4.zip](https://github.com/alerta/kibana-alerta/files/320889/Alerta-Kibana4.zip)
![alertakibana](https://cloud.githubusercontent.com/assets/19651158/16157684/8e7497d0-3487-11e6-98dc-4dad80f22b9f.png)

**Comment by satterly** [comment]
Thanks. See #3
