### ISSUE TITLE
Issues with Logstash and Elasticsearch

### ISSUE THREAD

**Issue by mikesand** [alerta/kibana-alerta#5]
Has anyone seen issues where logstash throws an exception that says:

{:timestamp=>"2016-11-03T23:59:49.722000+0000", :message=>"Failed action. ", :status=>400, :action=>["index", {:_id=>nil, :_index=>"logstash-2016.11.03", :_type=>"exceptionAlert", :_routing=>nil}, #<LogStash::Event:0xcb54625 @metadata_accessors=#<LogStash::Util::Accessors:0x19512df8 @store={}, @lut={}>, @cancelled=false,

and ends with:

:response=>{"create"=>{"_index"=>"logstash-2016.11.03", "_type"=>"exceptionAlert", "_id"=>"AVgsomPHj6CtXJTnVl4v", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [value]", "caused_by"=>{"type"=>"number_format_exception", "reason"=>"For input string: \"Down\""}}}}, :level=>:warn}

**Comment by gabrielcenersys** [comment]
I think I found the problem, it is in the Elasticsearch default mappings. In some cases we send alerts where the "value" is a number, on others a string.  If the first alert, after the elastisticsearch index has rolled, is a string, everything is good, but if it is a number, then we get this error everytime we get an alert with a string.  

in logstash-2016.11.03:

```
      "value" : {
                  "type" : "long"
               }
```

in logstash-2016.11.04:

```
     "value" : {
                  "fielddata" : {
                     "format" : "disabled"
                  },
                  "norms" : {
                     "enabled" : false
                  },
                  "type" : "string",
                  "fields" : {
                     "raw" : {
                        "index" : "not_analyzed",
                        "type" : "string",
                        "ignore_above" : 256
                     }
                  }
               }
```

If I set a default mapping for "value" as string, I believe the error will go away...  I will report back.

**Comment by gabrielcenersys** [comment]
I am confirming that the setting a default mapping for the field value has resolved the issue.  You can close this issue.

**Comment by satterly** [comment]
Great. Thanks for following this up.
